name: food
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "^3.6.1"

dependencies:
  google_fonts: ^6.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  image_picker: ^1.0.7
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Initial/       # Include all images inside the Initial folder
    - assets/               # Include general images from the assets folder
    - images/               # If you have used images from this folder

  fonts:
    - family: CedarvilleCursive
      fonts:
        - asset: fonts/CedarvilleCursive-Regular.ttf
#    - family: Trajan Pro
#      fonts:
#        - asset: fonts/TrajanPro.ttf
#        - asset: fonts/TrajanPro_Bold.ttf
#          weight: 700
